version: 0.9.{build}

pull_requests:
  do_not_increment_build_number: false
max_jobs: 1

environment:
    access_token:
      secure: XQvkhXxMw7yJPQF4xQe/OV5+u0Dhx0bsaXIHE2PNvPJr15qw+oA9SNlKYnGo6UNQ

    MSSQL_LOGIN: sa
    MSSQL_PASS: Password12!
    TSQLTSETCLR:  tests\tSQLt\SetClrEnabled.sql
    TSQLTCREATEDB: tests\tSQLt\CreateDatabase.sql
    TSQLTINSTALL: tests\tSQLt\tSQLt.class.sql
    TSQLTBUILDPATH: tests\build
    TSQLTTESTPATH: tests\run
    TARGET_DB: tSQLt
    
    matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      MSSQL: SQL2019
      DB_INSTANCE: (local)\SQL2019
      LINT_CONFIG: appveyor\tsqllint\.tsqllintrc_150
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSSQL: SQL2017
      DB_INSTANCE: (local)\SQL2017
      LINT_CONFIG: appveyor\tsqllint\.tsqllintrc_140
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSSQL: SQL2016
      DB_INSTANCE: (local)\SQL2016
      LINT_CONFIG: appveyor\tsqllint\.tsqllintrc_130
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSSQL: SQL2014
      DB_INSTANCE: (local)\SQL2014
      LINT_CONFIG: appveyor\tsqllint\.tsqllintrc_120
      
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSSQL: SQL2012SP1
      DB_INSTANCE: (local)\SQL2012SP1
      LINT_CONFIG: appveyor\tsqllint\.tsqllintrc_110

before_build:
  - git checkout %APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH% -q
  - git config --global credential.helper store
  - ps: Add-Content -Path "$env:USERPROFILE\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewLine

install:
- ps: Install-Module SqlServer -Force -AllowClobber
- npm install
- ps: .\appveyor\start_sqlserver.ps1
- ps: .\appveyor\install_tsqlt.ps1

build_script:
- ps: .\appveyor\make_combined_script.ps1
- ps: .\appveyor\install_expsql.ps1
- ps: .\appveyor\build_tsqlt_tests.ps1

test_script:
- ps: .\appveyor\run_tsqlt_tests.ps1
- echo Running TSQLLint tests
- npx tsqllint -c %LINT_CONFIG% *.sql

on_success:
- git config --global credential.helper store
- ps: Add-Content -Path "$env:USERPROFILE\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewLine
- git config --global user.email "appveyor@lowlydba.com"
- git config --global user.name "Appveyor"
- git add .
- git commit -a -m "CI produced files"
- git push --set-upstream express %APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH% -f