version: 1.5.{build}

pull_requests:
  do_not_increment_build_number: false
max_jobs: 2
skip_commits:
  message: CI produced files

environment:
  access_token:
    secure: 'E5I+i+CQyj9EHusDrPSQKHRXmzmpTujYAoFxlvJjvSRSEQHHzqTBIFR1VuPbwLMi'
  AZURE_SQL_PASS:
    secure: 'rYm3nE1kwpbdE7QtyLb8CjvA1ENjY3usz3Qqskf1TXU='

  APPVEYOR_RDP_PASSWORD: Np^VNSzJI5#OmRdUNqro2T9UVkCdZ
  TARGET_DB: tSQLt
  COV_REPORT: appveyor\sqlcover\Coverage.opencoverxml
  
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    MSSQL: SQL2019
    DB_INSTANCE: localhost\SQL2019
    LINT_CONFIG: appveyor\tsqllint\.tsqllintrc_150
    LATEST: True

  # Azure SQL Env
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    MSSQL: AZURESQL
    LINT_CONFIG: appveyor\tsqllint\.tsqllintrc_150
    TARGET_DB: expresssql
    DB_INSTANCE: expresssql.database.windows.net
    LATEST: False
    COV_REPORT: appveyor\sqlcover\Coverage_azuresql.opencoverxml
    AZURE_SQL_USER: lowlysa
    AzureSQL: True
    
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    MSSQL: SQL2017
    DB_INSTANCE: localhost\SQL2017
    LINT_CONFIG: appveyor\tsqllint\.tsqllintrc_140
    LATEST: False
    AzureSQL: False
    
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    MSSQL: SQL2016
    DB_INSTANCE: localhost\SQL2016
    LINT_CONFIG: appveyor\tsqllint\.tsqllintrc_130
    LATEST: False
    AzureSQL: False
    
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    MSSQL: SQL2014
    DB_INSTANCE: localhost\SQL2014
    LINT_CONFIG: appveyor\tsqllint\.tsqllintrc_120
    LATEST: False
    AzureSQL: False
    
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    MSSQL: SQL2012SP1
    DB_INSTANCE: localhost\SQL2012SP1
    LINT_CONFIG: appveyor\tsqllint\.tsqllintrc_110
    LATEST: False
    AzureSQL: False

clone_script:
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewLine
  - git config --global user.email "appveyor@lowlydba.com"
  - git config --global user.name "Appveyor"
  - git config --global core.safecrlf false
  - git clone -q --single-branch --branch=%APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH% https://github.com/LowlyDBA/dba-multitool.git %APPVEYOR_BUILD_FOLDER%
  - cd %APPVEYOR_BUILD_FOLDER%

install:
  - ps: .\appveyor\install_dependencies.ps1
  - ps: .\appveyor\start_sqlserver.ps1
  - ps: .\appveyor\install_tsqlt.ps1

build_script:
  - ps: .\appveyor\generate_combined_script.ps1
  - ps: .\appveyor\install_tool.ps1
  - ps: .\appveyor\build_tsqlt_tests.ps1

# Non-covered test run
test_script:
  - ps: .\appveyor\run_tsqllint.ps1
  - ps: .\appveyor\run_pester_tests.ps1

for:
# Latest SQL Server: Code cov & Upload
- 
  matrix:
    only:
      - LATEST: True

  # Setup codecov, SQL Cover
  before_test:
    - ps: .\appveyor\install_coverage_dependencies.ps1

  # Run tests with SQL Cover analysis
  test_script:
    - ps: .\appveyor\run_pester_tests.ps1 -CodeCoverage

  # Build markdown w/ sp_doc
  after_test:
    - ps: .\appveyor\generate_sample_markdown.ps1

  # Upload code coverage report, push generated files
  on_success:
    - codecov -f %COV_REPORT%
    - ps: .\appveyor\push_git_changes.ps1

# Azure SQL: No need to start SQL Server locally
-  
  matrix:
    only:
      - AzureSQL: True

  install:
    - ps: .\appveyor\install_dependencies.ps1
    - ps: .\appveyor\install_tsqlt.ps1
