name: 'TSQLLint'
author: '@LowlyDBA'
description: 'Lint T-SQL files'
inputs: 
# For some reason, need to do wildcard twice to get all recursive files/folders
  file-dir-1:
    description: 'First file/dir'
    required: true
    default: '*.sql'
  file-dir-2:
    description: 'Second file/dir'
    required: true
    default: '*.sql'
  config:
    description: 'Config file'
    required: false
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file-dir-1 }}
    - ${{ inputs.file-dir-2 }}
    - ${{ inputs.config }}
